#!/usr/bin/env bash
echo "=========================================="
echo "NTLOTTO v3: Sprint C (조합 생성)"
echo "=========================================="
echo "본 스크립트는 조합 생성을 위한 예시 커맨드를 안내합니다."
echo "조합 생성 모듈은 기본적으로 강력하게 잠겨(Disabled) 있습니다."
echo "사용하려면 환경변수와 플래그를 제공해야 합니다."
echo ""
echo "실행 예시 (bash / linux / macOS):"
echo "export ALLOW_COMBO_GENERATION=1"
echo "python -m ntlotto.cli.generate_combos_cli --round 1212 --n 10 --i_understand_and_allow_generation"
echo ""
echo "실행 예시 (Windows PowerShell):"
echo "\$env:ALLOW_COMBO_GENERATION=\"1\""
echo "python -m ntlotto.cli.generate_combos_cli --round 1212 --n 10 --i_understand_and_allow_generation"
echo "=========================================="
